### PR TITLE
Fix Quarkus misspelled config properties & use QuarkusComponentTest

### LINKED ISSUE #1383: Quarkus Component Test + fix properties
In Quarkus, the unit tests for the producer are mocks that do not really test anything. We can use `@QuarkusComponentTest` like in https://quarkus.io/guides/testing-components

During the rework, we noticed for carbon aware job processing some property names are incorrect (this will be a **breaking change**).

### PR DESCRIPTION
**Pull request by brainbaking**
Fixes #1383

This PR has the following **breaking changes**:

- The Quarkus configuration properties for carbon aware job processing was incorrectly prefixed with `quarkus.jobrunr.background-job-server.carbon-aware-job-processing-configuration` instead of `quarkus.jobrunr.background-job-server.carbon-aware-job-processing`. These are now aligned with Spring/Micronaut and the docs; e.g.

```
quarkus.jobrunr.background-job-server.carbon-aware-job-processing.enabled=true
quarkus.jobrunr.background-job-server.carbon-aware-job-processing.area-code=FR
quarkus.jobrunr.background-job-server.carbon-aware-job-processing.api-client-connect-timeout=500ms
quarkus.jobrunr.background-job-server.carbon-aware-job-processing.api-client-read-timeout=300ms
quarkus.jobrunr.background-job-server.carbon-aware-job-processing.poll-interval-in-minutes=15
```

- Also, the two above timeouts are now `Duration`s instead of `Integer`s: please explicitly provide a unit.
- Property `quarkus.jobrunr.background-job-server.succeeded-job-request-size` becomes `quarkus.jobrunr.background-job-server.succeeded-jobs-request-size` (notice plural jobs)
- Property `quarkus.jobrunr.background-job-server.awaiting-job-request-size` becomes `quarkus.jobrunr.background-job-server.awaiting-jobs-request-size` (notice plural jobs)

### CODE REVIEW

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/main/java/org/jobrunr/quarkus/autoconfigure/JobRunrRuntimeConfiguration.java [hunk 1]
```diff
@@ -240,14 +241,14 @@ interface CarbonAwareJobProcessingConfiguration {
         Optional<String> externalCode();
 
         /**
-         * Allows to set the connect timeout for the carbon api client
+         * Allows to set the connect timeout for the carbon api client in minutes
          */
-        Optional<Integer> apiClientConnectTimeoutMs();
+        Optional<Integer> apiClientConnectTimeout();
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/main/java/org/jobrunr/quarkus/autoconfigure/JobRunrRuntimeConfiguration.java]: Can we move the type to `Optional<Duration>`? That would match Spring Boot configuration.

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/main/java/org/jobrunr/quarkus/autoconfigure/JobRunrRuntimeConfiguration.java [hunk 2]
```diff
@@ -240,14 +241,14 @@ interface CarbonAwareJobProcessingConfiguration {
...
 
         /**
-         * Allows to set the read timeout for the carbon api client
+         * Allows to set the read timeout for the carbon api client in minutes
          */
-        Optional<Integer> apiClientReadTimeoutMs();
+        Optional<Integer> apiClientReadTimeout();
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/main/java/org/jobrunr/quarkus/autoconfigure/JobRunrRuntimeConfiguration.java]: Can we move the type to `Optional<Duration>`? That would match Spring Boot configuration.

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/dashboard/JobRunrDashboardDisabledProducerTest.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+import jakarta.enterprise.inject.spi.CDI;
+import jakarta.inject.Inject;
+import org.jobrunr.dashboard.JobRunrDashboardWebServer;
+import org.junit.jupiter.api.Test;
+
+import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
+
+@QuarkusComponentTest
+@TestProfile(JobRunrDashboardDisabledProducerTest.class)
+public class JobRunrDashboardDisabledProducerTest implements QuarkusTestProfile {
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/dashboard/JobRunrDashboardDisabledProducerTest.java]: I'd like to avoid having a class just for testing disabled. Can't this be in the main test class?

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/JobRunrProducerJobSchedulerDisabledTest.java [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+import jakarta.inject.Inject;
+import org.jobrunr.scheduling.JobRequestScheduler;
+import org.jobrunr.scheduling.JobScheduler;
+import org.junit.jupiter.api.Test;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+// Must be in another test as Quarkus initializes the test context once per class
+@QuarkusComponentTest
+public class JobRunrProducerJobSchedulerDisabledTest {
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/JobRunrProducerJobSchedulerDisabledTest.java]: Same as elsewhere: I'd like to avoid having a class just for testing disabled. Can't this be in the main test class?

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle [hunk 5]
```diff
@@ -50,7 +50,9 @@ dependencies {
     testImplementation testFixtures(project(":core"))
     testImplementation 'com.fasterxml.jackson.core:jackson-databind'
     testImplementation 'org.eclipse:yasson'
-    testImplementation 'org.mongodb:mongodb-driver-sync'
+     testImplementation 'org.mongodb:mongodb-driver-sync'
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle]: Indentation issue?

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/server/JobRunrBackgroundJobServerProducerCustomWorkerPolicyTest.java [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+import org.jobrunr.server.strategy.BasicWorkDistributionStrategy;
+import org.jobrunr.server.strategy.WorkDistributionStrategy;
+import org.jobrunr.server.threadpool.JobRunrExecutor;
+import org.jobrunr.server.threadpool.PlatformThreadPoolJobRunrExecutor;
+import org.junit.jupiter.api.Test;
+
+import static org.jobrunr.JobRunrAssertions.assertThat;
+
+@QuarkusComponentTest
+public class JobRunrBackgroundJobServerProducerCustomWorkerPolicyTest {
```
Comment (auloin) [inline framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/server/JobRunrBackgroundJobServerProducerCustomWorkerPolicyTest.java]: I'm not totally against this one but isn't it possible to integrate it in the main `BackgroundJobServerProducer` test?

Comment (brainbaking) [reply framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/server/JobRunrBackgroundJobServerProducerCustomWorkerPolicyTest.java]: No. Believe me, I tried 😇 Quarkus test profile interference. Doesn't work with `@Nested` either...

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle (hunk 5 above)
Comment (brainbaking) [reply framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle]: Weird, didn't touch that? fixed as well

File: framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/JobRunrProducerJobSchedulerDisabledTest.java (hunk 4 above)
Comment (brainbaking) [reply framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/src/test/java/org/jobrunr/quarkus/autoconfigure/JobRunrProducerJobSchedulerDisabledTest.java]: Nope.

**Comment by brainbaking** [comment]
> Is this wip? Asking because it seems like some tests in spring are missing here. Anyway here are some early feedback.

The json serialization tests use Spring's `FilteredClassLoader` and I have trouble mimicking that in Quarkus but I'll give it another go. (Edit: already covered in `JobRunrExtensionProcessorTest` as unit tests) Same for storage provider config. Otherwise, this PR contains more tests than before for Quarkus.

**Comment by brainbaking** [comment]
@auloin ah nice `Instance<>` seems to be the part of the missing puzzle 👍
